import styles from '../styles/Home.module.css'
import Head from 'next/head'
import React from 'react'
import {useSelector} from 'react-redux'
import Sidebar from '../components/sidebar/sidebar';
import Chat from '../components/chat/chat';


export default function Home() {
  const user = useSelector(state => state.user)
  const letter = user.info ? user.info.username[0].toLowerCase() : undefined;
  


  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/twitter.png" />
      </Head>
      <div className={styles.container}>
        <main className={styles.home}>
          <Sidebar letter={letter}/>
          <Chat/>
        </main>
      </div>
    </>
  )
}
