import styles from '../styles/Home.module.css'
import Head from 'next/head'
import React, {useState, useEffect} from 'react'
import store from '../redux/store'
import ContentWrapper from '../components/home/contentWrapper';
import SendTweet from '../components/home/sendTweet';
import Tweet from '../components/home/tweet';
import Trends from '../components/home/trends';
import {useSelector} from 'react-redux'
import { addNewTweet, fetchTweets, like, comment } from '../redux/reducers/tweetsReducer'
import { logout } from '../redux/reducers/userReducer'
import Sidebar from '../components/sidebar/sidebar';
import Input from '../components/ui_items/input';
import io from 'socket.io-client';

function useSocket(url) {
  const [socket, setSocket] = useState(null)

  useEffect(() => {
    const socketIo = io(url)

    setSocket(socketIo)

    function cleanup() {
      socketIo.disconnect()
    }
    return cleanup

    // should only run once and not on every re-render,
    // so pass an empty array
  }, [])

  return socket
}

export default function Home() {
  const [tweet, setTweet] = useState('')
  const [tweets, setTweets] = useState([])
  const state = useSelector(state => state.tweets)
  const user = useSelector(state => state.user)
  const letter = user.info ? user.info.username[0].toLowerCase() : undefined;
  const [messeges, setMessages] = useState([])
  const socket = useSocket('http://localhost:1374')

  useEffect(() => {
    const handleNewMessage = (mes) => {
      console.log(messeges)
      // const newArr = [...messeges,mes] 
      setMessages(()=>[...messeges,1,2,3]);
    }

    if (socket) {
      socket.on('message', ({data}) => {
        handleNewMessage(data)
      },)
    }
  }, [socket])

  useEffect(() => {
    if(user.jwt !== undefined){
      store.dispatch(fetchTweets({jwt: user.jwt}))
    } 
  }, [user])

  useEffect(() => {
    if(user.jwt !== undefined){
      console.log([...state.tweets])
      const myTweets = [...state.tweets] 
      setTweets(myTweets.reverse())
    } 
  }, [state])

  const handleSubmitNewMessage = () => {
    socket.emit('message', { data: Date.now() })
  }

  const sendTweet = (tweetText) => {
    const str = tweetText.replaceAll('<div>','').replaceAll('</div>','').replaceAll('<br>',' ')
    store.dispatch(addNewTweet({
      content: str,
      author: user.info.email,
      username: user.info.username,
      authorId: user.info.id,
      jwt: user.jwt
    }))
    
  }

  const sendComment = ({content, tweetId}) => {
    store.dispatch(comment({
      content,
      tweetId,
      username: user.info.username,
      jwt: user.jwt
    }))
  }

  const clickLogout = () => {
    store.dispatch(logout())
  }

  const likeClick = ({tweetId}) => {
    store.dispatch(like({
      tweetId: tweetId,
      userId: user.info.id,
      jwt: user.jwt,
    }))
  }


  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/twitter.png" />
      </Head>
      <div className={styles.container}>
        <main className={styles.home}>
          <Sidebar letter={letter}/>
          
          <ContentWrapper>
            <div className={styles['home_content-section_title']}>
              <h3 onClick={clickLogout}>Home</h3>
              {messeges.map((item, key)=> 
                <h5 key={key}>{item}</h5>
              )}
            </div>
            <SendTweet setTweet={(val)=>setTweet(val)} letter={letter} tweet={tweet} sendTweet={sendTweet}/>
            {tweets.map((item, key)=> 
              <Tweet tweetInfo={item} key={key} like={(id)=>likeClick(id)} sendComment={sendComment}/>
            )}
          </ContentWrapper>
          <div className={styles['home_propose-section']}>
            <Input/>
            <Trends/>
          </div>
        </main>
      </div>
    </>
  )
}
