import styles from '../styles/Auth.module.css'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import React, { useState } from 'react'
import store from '../redux/store'
import { login } from '../redux/reducers/userReducer'

// import Image from 'next/image'

export default function Signin() {
  const [password, setPassword] = useState('')
  const [email, setEmail] = useState('')
  const router = useRouter();

  const signin = () => {
    // console.log(email)
    // console.log(password)

    store.dispatch(login({
      email: email,
      password: password
    }))

    router.push('/')
    
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Log in</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/twitter.png" />
      </Head>
      <main className={styles['auth_main']}>
        <div className={styles['auth-image-side']}>
          <div className={styles['svg_chirp']}>
            <Image src="/twitter.svg"  height={330} width={330} />
          </div>
          <div className={styles['auth-image']}>
          </div>
        </div>
        
        <div className={styles['auth-content-side']}>
          <div>
            <Image src="/twitter2.svg"  height={42} width={42} />
          </div>
          <h2 className={styles['auth-content-side_title']}>
            Happening now
          </h2>
          <h3 className={styles['auth-content-side_sub-title']}>
            Log in 
          </h3>
          <form className={styles['auth-form']}>
            <label className={styles['auth-label']} htmlFor="email">Email</label>
            <input onChange={(e) => setEmail(e.target.value)} value={email} className={styles['auth-input']} type="text" id="email" name="email" placeholder="Your last name.." />
            <label className={styles['auth-label']} htmlFor="password">Password</label>
            <input onChange={(e) => setPassword(e.target.value)} value={password} className={styles['auth-input']} type="password" id="password" name="password" placeholder="Your password.." />
          </form>
          <button  onClick={signin} className={styles['auth-submit']} defaultValue="Submit">Submit</button>
          <div className={styles['auth-policy']}>
            By signing up, you agree to the <span className={styles['auth-policy-span']}>Terms of Service</span> and <span className={styles['auth-policy-span']}>Privacy Policy</span>, including <span className={styles['auth-policy-span']}>Cookie Use</span>.
          </div>
          <div className={styles['auth-oposite-auth']}>
            Already have an account? <span onClick={()=>router.push('/signup')} className={styles['auth-oposite-auth-span']}>Sign up</span>
          </div>
        </div>
      </main>
    </div>
  )
}
